title: Zhiyuan Pan's Homepage
page-top-title: Zhiyuan Pan
top-section-bg-text: Computer Science
home-subtitle: Zhiyuan Pan&ensp;|&ensp;潘致远
copyright-text: '&copy; Zhiyuan Pan 2023-2024. All Rights Reserved.'
